### ISSUE TITLE
transactions_sync doesn't accept cursor or count

### ISSUE THREAD

**Issue by thomasmost** [libninjacom/plaid-rs#2]
See my implementation here: https://github.com/Bend-Green/plaid-rs/blob/main/src/transactions.rs#L194-L211

**Comment by kurtbuilds** [comment]
Because these are optional parameters, they get applied with function chaining. Example:

```rust
client.transactions_sync("my-access-token")
    .count(500)
    .cursor("my_cursor".to_string())
    .send()
    .await
```

Let me know if that doesn't work or you encounter issues.

For devxp, I noticed that cursor still takes a `String`. Since you're using the API, I'm curious your opinion: is it easier to take a reference or owned type in that case? I notice your code takes an owned type.

**Comment by thomasmost** [comment]
ah!

**Comment by kurtbuilds** [comment]
This toolchain is relatively new, so I'm still ironing kinks out. Do you think that the cleanest way for this API to work, or would you make changes?

Does it make sense to close out #2, #1, and #3 at this point?

**Comment by thomasmost** [comment]
Yep, I'll close them.

**Comment by kurtbuilds** [comment]
Quick update, I added short documentation to each `Request` object, so that can hopefully serve as a pointer for other people who might have the same question.
