### ISSUE TITLE
Missing Models

### ISSUE THREAD

**Issue by Overdash** [libninjacom/plaid-rs#7]
V4 had `PaymentStatusUpdateWebhook` which is still [present in the Python version](https://github.com/plaid/plaid-python/blob/master/plaid/model/payment_status_update_webhook.py) of the SDK.

V5 does not have this model (or perhaps I cannot find it?)

Not sure if this was missed in Generation, but it's possible other models were also skipped (I see a couple Webhook based models misplaced)

**Comment by kurtbuilds** [comment]
Thanks for catching this.

Between v4 and v5, I implemented model pruning, to prevent generating models that are unused. Since weebhook models are "inbound", they're not part of the OpenAPI spec, and therefore were pruned.

I carved out webhooks from the pruning, so they're included again.

Updated to the latest version of the OpenAPI spec, included webhook models, and published as v6. Enjoy!
