### ISSUE TITLE
expose products in link_token_create

### ISSUE THREAD

**Issue by iJustErikk** [libninjacom/plaid-rs#8]
products needs to be exposed, as it is required by plaid.

I can send in a PR for this. Until then, I'll be looking for a workaround.

**Comment by kurtbuilds** [comment]
Happy to take a PR

**Comment by iJustErikk** [comment]
Ah, I just realized LinkTokenCreateRequest is a builder. I could have caught that if I read the example better. I think creating the request without initially using the builder implies that creating the request is terminal and it is not a builder. So I guess my eyes skipped over it.

I also wonder why we take in borrows just to clone them? I think we could work entirely with borrows or have the user clone as needed.

I'll open a PR, as it is required by Plaid now.

**Comment by kurtbuilds** [comment]
Got it. Yeah all the methods are builders.

I just checked the OpenAPI spec, and unfortunately plaid hasn't updated that field to specify that it's required. That said, they do have a track record of not keeping their spec up to date. Are you sure it is a required field? 

https://github.com/plaid/plaid-openapi/blob/master/2020-09-14.yml

EDIT: I just checked the docs, and `products` is not marked as required. See:

https://plaid.com/docs/api/tokens/#link-token-create-request-products

So merging your PR was premature on my end. Let me know if you have a justification for why the docs are wrong, otherwise I'll revert the PR merge.

**Comment by iJustErikk** [comment]
If you hit it without specifying products, you'll get an error back from the API. Let me hit it real quick to show you what you will get.

Code:
client.link_token_create(LinkTokenCreateRequired { client_name: "test", country_codes: &["US"], language: "en", user: LinkTokenCreateRequestUser {client_user_id: "test", address: None, date_of_birth: None, email_address: None, email_address_verified_time: None, id_number: None, legal_name: None, name: None, phone_number: None, phone_number_verified_time: None, ssn: None }  }).await;

Here is what I got:

{
  "display_message": null,
  "documentation_url": "https://plaid.com/docs/?ref=error#invalid-request-errors",
  "error_code": "INVALID_FIELD",
  "error_message": "must provide at least one product",
  "error_type": "INVALID_REQUEST",
  "request_id": "4SsbXcJjrbNmiwW"
}

OH shoot, I see:

List of Plaid product(s) you wish to use. If launching Link in update mode, should be omitted (unless you are using update mode to add Income or Assets to an Item); required otherwise.

Let's revert that. I missed the fact that it is conditionally required. Sorry about that.

I think maybe the sdk should reflect two choices of update or non-update mode with the link token. Maybe we could split it into two methods or maybe take in an enum that has 2 variants.

**Comment by kurtbuilds** [comment]
Not a bad idea. I reverted. That said, that would require customizing the SDK beyond what comes directly from the OpenAPI spec.

I'll close for now but feel free to revisit if related problems show up.
